### ISSUE TITLE
No minitest 

### ISSUE THREAD

**Issue by muhammetfaik** [thoughtfulml/examples#7]
```
 2-k-nearest-neighbors git:(master) ✗ bundle exec rake 
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -w -I"lib:lib" -I"/Library/Ruby/Gems/2.3.0/gems/rake-12.3.2/lib" "/Library/Ruby/Gems/2.3.0/gems/rake-12.3.2/lib/rake/rake_test_loader.rb" "test/lib/face_spec.rb" "test/lib/image_spec.rb" "test/lib/neighborhood_spec.rb" 
/Users/mordekay/Codes/examples/2-k-nearest-neighbors/test/lib/face_spec.rb:12: warning: assigned but unused variable - actual_md5
/Users/mordekay/Codes/examples/2-k-nearest-neighbors/test/lib/face_spec.rb:13: warning: assigned but unused variable - expected_md5

File does not exist: minitest/autorun

rake aborted!
Command failed with status (1): [ruby -w -I"lib:lib" -I"/Library/Ruby/Gems/2.3.0/gems/rake-12.3.2/lib" "/Library/Ruby/Gems/2.3.0/gems/rake-12.3.2/lib/rake/rake_test_loader.rb" "test/lib/face_spec.rb" "test/lib/image_spec.rb" "test/lib/neighborhood_spec.rb" ]
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
➜  2-k-nearest-neighbors git:(master) 
```

Sorry Help !!!
what should I do ?

**Comment by hexgnu** [comment]
Hello there,

I will take a look today. Minitest has gone through lots of changes so it might be something simple.

-Matt

**Comment by hexgnu** [comment]
Hey there, I just put minitest in the gemfile. That should fix the problem.

Thanks!
